version: '3.7'


services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
       - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=@Elejota1010
        - POSTGRES_DB=ignite
    volumes:
        - pgdata:/data/postgres
  app:
    build: . 
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata: